use std::sync::mpsc::Sender;

use crate::app::{InstallConfig, InstallMessage, InstallMode};

use super::{run_sudo, command_ok};

pub fn generate(config: &InstallConfig, mode: InstallMode, tx: &Sender<InstallMessage>) -> Result<(), String> {
    // Create directories
    run_sudo("mkdir", &["-p", &config.install_dir, &config.data_dir])?;
    run_sudo("mkdir", &["-p", &format!("{}/config", config.install_dir)])?;

    // Generate production.toml for Rust backend
    if mode.needs_backend() {
        tx.send(InstallMessage::Progress("Generating config/production.toml...".to_string())).ok();
        let toml_content = format!(
            r#"[server]
port = {}

[cron]
enabled = true
"#,
            config.api_port
        );
        write_file(
            &format!("{}/config/production.toml", config.install_dir),
            &toml_content,
        )?;
    }

    // Generate .env file
    tx.send(InstallMessage::Progress("Generating .env file...".to_string())).ok();

    let mut env_lines = vec![
        "# RustBill Configuration".to_string(),
        "# Generated by rustbill-installer".to_string(),
        String::new(),
    ];

    if mode.needs_database() {
        env_lines.push(format!("DATABASE_URL={}", config.database_url()));
    }

    if mode.needs_backend() {
        env_lines.push("RUN_MODE=production".to_string());
        env_lines.push("RUST_LOG=rustbill_server=info,rustbill_core=info".to_string());
        env_lines.push(format!("CRON_SECRET={}", config.cron_secret));
    }

    env_lines.push(String::new());

    if mode.needs_frontend() {
        let backend_url = if matches!(mode, InstallMode::FrontendOnly) {
            config.rust_backend_url.clone()
        } else {
            format!("http://localhost:{}", config.api_port)
        };
        env_lines.push(format!("RUST_BACKEND_URL={}", backend_url));
        env_lines.push("NODE_ENV=production".to_string());
        env_lines.push(format!("PORT={}", config.frontend_port));
    }

    let env_content = env_lines.join("\n") + "\n";
    write_file(&format!("{}/.env", config.install_dir), &env_content)?;

    // Set permissions
    tx.send(InstallMessage::Progress("Setting file permissions...".to_string())).ok();
    let _ = run_sudo("chmod", &["640", &format!("{}/.env", config.install_dir)]);

    // Create system user if needed
    if mode.needs_services() {
        tx.send(InstallMessage::Progress("Creating system user 'rustbill'...".to_string())).ok();
        let _ = run_sudo("useradd", &["--system", "--shell", "/usr/sbin/nologin", "--home-dir", &config.install_dir, "rustbill"]);
        let _ = run_sudo("chown", &["-R", "rustbill:rustbill", &config.install_dir]);
        let _ = run_sudo("chown", &["-R", "rustbill:rustbill", &config.data_dir]);
    }

    Ok(())
}

fn write_file(path: &str, content: &str) -> Result<(), String> {
    // Write to tmp then move with sudo
    let tmp_path = format!("/tmp/rustbill-config-{}", std::process::id());
    std::fs::write(&tmp_path, content)
        .map_err(|e| format!("Failed to write temp file: {}", e))?;
    let out = run_sudo("mv", &[&tmp_path, path])?;
    if !command_ok(&out) {
        return Err(format!("Failed to move config to {}", path));
    }
    Ok(())
}
