//! Password hashing compatibility layer.

pub use super::service::{hash_password, verify_password};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_argon2_hash_and_verify() {
        let hash = hash_password("test123").unwrap();
        assert!(hash.starts_with("$argon2"));
        assert!(verify_password("test123", &hash).unwrap());
        assert!(!verify_password("wrong", &hash).unwrap());
    }

    #[test]
    fn test_bcrypt_compat() {
        // Hash generated by Node.js bcryptjs
        let bcrypt_hash = bcrypt::hash("admin123", 10).unwrap();
        assert!(verify_password("admin123", &bcrypt_hash).unwrap());
        assert!(!verify_password("wrong", &bcrypt_hash).unwrap());
    }
}
